server:
  port: 8080

spring:
  application:
    name: courses-example
  datasource:
    url: jdbc:postgresql://localhost:5432/courses-example
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect