server:
  port: 8080

spring:
  application:
    name: coursesdb
  datasource:
    url: jdbc:h2:file:./database/testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
